CREATE TABLE ACAO_RETORNO (
    ID               INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TIPO_RETORNO_ID  INTEGER NOT NULL,
    ACAO             VARCHAR(255) NOT NULL,
    TITULO           VARCHAR(255) NOT NULL
);

CREATE TABLE SERVENTIAS (
	ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
	COMARCA varchar(500) NOT NULL,
	CODIGO_TJ INTEGER NOT NULL,
	DESCRICAO Varchar(500) NOT NULL,
	TITULAR varchar(500) NOT NULL,
	ATIVO varchar(1) NOT NULL DEFAULT 'S'
);

CREATE TABLE BOTMENU (
    ID              INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRICAO       VARCHAR(300) NOT NULL,
    MENU_SEQUENCIA  INTEGER NOT NULL,
    MENU_PAI_ID     INTEGER,
    ACAO_MENU_ID    INTEGER,
    SERVENTIA_ID 	BIGINT,
    FOREIGN KEY (SERVENTIA_ID) REFERENCES SERVENTIAS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (MENU_PAI_ID) REFERENCES BOTMENU(ID) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (ACAO_MENU_ID) REFERENCES ACAO_RETORNO(ID) ON UPDATE SET NULL ON DELETE SET NULL
);

