INSERT INTO SERVENTIAS
(COMARCA, CODIGO_TJ, DESCRICAO, TITULAR)
VALUES
('NITEROI', 9641, 'NITEROI - 1 OFICIO DE NOTAS', 'LAECIO DUARTE SILVA'),
('NITEROI', 9643, 'NITEROI - 3 OFICIO DE NOTAS', 'FERNANDO CESAR DE AZEVEDO'),
('SAO DOMINGOS DO CAPIM', 439, 'CARTÓRIO MARIA DA PENHA - PA', 'LOHANNA COSBER BITTI'),
('NITEROI', 1076, 'CENTRAL RTD NITEROI', 'WILLIAM FELISBERTO FAGUNDES'),
('NOVA IGUACU', 1680, 'CENTRAL RTD NOVA IGUACU', 'LUCINEIA BARBOSA FURTADO');

INSERT INTO ACAO_RETORNO
(TIPO_RETORNO_ID, ACAO, TITULO)
VALUES
	(0, 'TEXTO_PRINCIPAL', 'Atendimento iniciado. Por favor, selecione o atendimento desejado, dentro de uma das opções abaixo:'),
	(0, 'QUERY_RGI', 'Por favor informe o número do Protocolo ou Talão para consulta:'),
	(0, 'QUERY_FIRMAS', 'Por favor informe o número do CPF para consulta:');

INSERT INTO BOTMENU
	(DESCRICAO, MENU_SEQUENCIA, MENU_PAI_ID, ACAO_MENU_ID, SERVENTIA_ID)
(SELECT 'MENU_PRINCIPAL', 1, NULL, A.ID, S.ID
	FROM SERVENTIAS S
	INNER JOIN ACAO_RETORNO A ON A.ACAO = 'TEXTO_PRINCIPAL');

INSERT INTO BOTMENU
	(DESCRICAO, MENU_SEQUENCIA, MENU_PAI_ID, ACAO_MENU_ID, SERVENTIA_ID)
(	
	SELECT CASE WHEN A.ACAO = 'QUERY_RGI' THEN 'Registros' ELSE 'Firmas' END AS descricao, 
		CASE WHEN A.ACAO = 'QUERY_RGI' THEN 1 ELSE 2 END AS sequencia, 
	B.ID AS MENU_PAI, A.ID AS ACAO, S.ID AS SERVENTIA
	FROM SERVENTIAS S
	INNER JOIN ACAO_RETORNO A ON A.ACAO <> 'TEXTO_PRINCIPAL'
	INNER JOIN BOTMENU B WHERE B.MENU_PAI_ID IS NULL AND S.ID = B.SERVENTIA_ID
);

